bajiao-weixin/config/routes.rb
Bajiao::Application.routes.draw do

  scope :path => "/weixin", :via => :post, :defaults => {:format => 'xml'} do
    root :to => 'weixin/home#welcome', :constraints => Weixin::Router.new(:type => "text", :content => "Hello2BizUser")
    root :to => 'weixin/staffs#show', :constraints => Weixin::Router.new(:type => "text", :content => /^@/)
    root :to => 'weixin/staff_photos#update', :constraints => Weixin::Router.new(:type => "text", :content=>/^#photo /)
    root :to => 'weixin/staffs#index', :constraints => Weixin::Router.new(:type => "text")
    root :to => 'weixin/staff_photos#create', :constraints => Weixin::Router.new(:type => "image")
  end

  get "/weixin" => "weixin/home#show"

  resources :staffs
  resources :staff_photos

  namespace :admin do
    resources :staffs
    resources :weixin_users
    resources :staff_photos do
      member do
        post 'change_valid'
      end
    end

    match '/roster_reset/staff' => 'roster_reset#staff'
    match '/roster_reset/photo' => 'roster_reset#photo'

    resource :session

    match '/' => redirect("/admin/staffs")
  end

end

bajiao-weixin/app/models/staff_photo.rb
# -*- encoding : utf-8 -*-
require 'net/http'
Net::HTTP.version_1_2

class StaffPhoto < ActiveRecord::Base
  S_INVALID = 1 # 未通过
  S_VALID = 2 # 通过审核

  attr_accessible :file, :staff_workno, :weixin_user_id

  belongs_to :staff, :foreign_key => "staff_workno", :primary_key => "workno"
  belongs_to :weixin_user

  before_create :resize_photo

  paginates_per 50

  validate :valid_file_size

  scope :valid, where(:status => S_VALID)

  # 根据上传数据新建
  def self.new_by_upload(params)
    photo = StaffPhoto.new(params)
    photo.file_name = params[:file].try(:original_filename)
    photo.content_type = params[:file].content_type
    photo.status = S_INVALID
    return photo
  end

  # 根据微信消息新建
  def self.new_by_msg(msg)
    photo = StaffPhoto.new
    weixin_user = WeixinUser.where(:weixin_id => msg.from_user).first
    photo.weixin_user_id = weixin_user.id
    photo.file_name = msg.pic_url
    photo.status = S_INVALID

    # 5秒限制
    Thread.new do
      file = Net::HTTP.get(URI(msg.pic_url))
      photo.file = file
      photo.content_type = "image/jpeg"
      photo.file_size = file.length
      photo.save
    end

    photo.save
    weixin_user.update_attribute(:tmp_photo_id, photo.id)
    return photo
  end

  # 校验文件大小
  def valid_file_size
    errors[:file] << "不能超过 1MB" if file.present? and file.size > 1.megabytes
  end

  # 调整图片尺寸
  def resize_photo
    return if file.blank?
    img = MiniMagick::Image.read(file)
    img.resize "300x400>"
    self.file = img.to_blob
    self.file_size = img.to_blob.length
  end

  def is_valid?
    return status != S_INVALID
  end
end

bajiao-weixin/app/controllers/admin/staff_photos_controller.rb
# -*- encoding : utf-8 -*-
class Admin::StaffPhotosController < Admin::ApplicationController

  def index
    @staff_photos = StaffPhoto.order("created_at DESC")
    @staff_photos = @staff_photos.where(:status=>params[:status]) if params[:status].present?
    @staff_photos = @staff_photos.page(params[:page])
  end

  def destroy
    @staff_photo = StaffPhoto.find(params[:id])
    @staff_photo.destroy

    redirect_to :back
  end

  def create
    @photo = StaffPhoto.new_by_upload(params)

    if @photo.save
      redirect_to :action => "index"
    else
      render :action => "index"
    end
  end

  def change_valid
    @staff_photo = StaffPhoto.find(params[:id])
    @staff_photo.update_attribute(:status, @staff_photo.is_valid? ? StaffPhoto::S_INVALID : StaffPhoto::S_VALID)

    redirect_to :back
  end
end

bajiao-weixin/app/controllers/staff_photos_controller.rb
# -*- encoding : utf-8 -*-
class StaffPhotosController < ApplicationController
  # 具体图片
  def show
    @staff_photo = StaffPhoto.find(params[:id])

    send_data @staff_photo.file, :type => @staff_photo.content_type, :disposition => 'inline'
  end
end

bajiao-weixin/app/controllers/weixin/staff_photos_controller.rb
# -*- encoding : utf-8 -*-
class Weixin::StaffPhotosController < Weixin::ApplicationController

  # 图片投稿
  def create
    @photo = StaffPhoto.new_by_msg(weixin_xml)
  end

  # 改变图片的归属
  def update
    workno = weixin_xml.content.split(' ')[1]
    @staff = Staff.where(:workno => workno).first
    photo = @weixin_user.tmp_photo
    if @staff.present? and photo.present?
      photo.update_attribute(:staff_workno, workno)
      @weixin_user.update_attribute(:tmp_photo_id, nil)
      render "update"
    else
      render "error"
    end
  end

end

bajiao-weixin/app/helpers/staff_photos_helper.rb
# -*- encoding : utf-8 -*-
module StaffPhotosHelper
end

bajiao-weixin/app/views/admin/staff_photos/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <%= render :partial => 'layouts/admin_nav', :locals => {:curr_tab => 'staff_photo'} %>

    <%= form_tag "/admin/staff_photos", :class => "form-inline", :multipart => true do %>
        <input type="file" name="file" style="width: 150px;"/>
        <input type="text" name="staff_workno" class="input-small" placeholder="工号" required/>
        <button class="btn">上传</button>
    <% end %>

    <div>
      <form action="/admin/staff_photos" method="get" class="form-inline">
        <select name="status" onchange="this.parentNode.submit()">
          <option value="">全部</option>
          <option <%= "selected" if StaffPhoto::S_INVALID.to_s == params[:status] %> value="<%= StaffPhoto::S_INVALID %>">未通过</option>
          <option <%= "selected" if StaffPhoto::S_VALID.to_s == params[:status] %> value="<%= StaffPhoto::S_VALID %>">已通过</option>
        </select>
      </form>
    </div>

    <%= paginate @staff_photos %>

    <table class="table table-hover table-bordered">
      <thead>
      <tr>
        <td width="3%">#</td>
        <th width="350px">图片</th>
        <th width="10%">归属人</th>
        <th width="15%">文件名</th>
        <th width="5%">文件大小</th>
        <th width="10%">上传者</th>
        <th width="10%">状态</th>
        <th></th>
      </tr>
      </thead>

      <% @staff_photos.each do |photo| %>
          <tr>
            <td><%= photo.id %></td>
            <td><%= image_tag staff_photo_path(photo) %></td>
            <td>
              <% if photo.staff_workno.present? %>
                  <%= photo.staff.try(:name) %>[<%= photo.staff_workno %>]
              <% end %>
            </td>
            <td style="word-wrap: break-word;word-break: break-all;"><%= photo.file_name %></td>
            <td><%= number_to_human_size photo.file_size %></td>
            <td>
              <% if photo.weixin_user.present? %>
                  <%= photo.weixin_user.nick %>(<%= photo.weixin_user.weixin_id %>)
              <% end %>
            </td>
            <td><%= status_desc photo %></td>
            <td>
              <%= link_to photo.is_valid? ? "拒绝" : "通过", change_valid_admin_staff_photo_path(photo), :class => "btn btn-primary", :method => :post %>
              <%= link_to "删除", admin_staff_photo_path(photo), :class => "btn btn-danger", :method => :delete, :confirm => "确定删除？" %>
            </td>
          </tr>
      <% end %>
    </table>

    <%= paginate @staff_photos %>
  </div>
</div>
<%= javascript_include_tag 'admin_staff_photos' %>