bajiao-weixin/config/routes.rb
Bajiao::Application.routes.draw do

  scope :path => "/weixin", :via => :post, :defaults => {:format => 'xml'} do
    root :to => 'weixin/home#welcome', :constraints => Weixin::Router.new(:type => "text", :content => "Hello2BizUser")
    root :to => 'weixin/staffs#show', :constraints => Weixin::Router.new(:type => "text", :content => /^@/)
    root :to => 'weixin/staff_photos#update', :constraints => Weixin::Router.new(:type => "text", :content=>/^#photo /)
    root :to => 'weixin/staffs#index', :constraints => Weixin::Router.new(:type => "text")
    root :to => 'weixin/staff_photos#create', :constraints => Weixin::Router.new(:type => "image")
  end

  get "/weixin" => "weixin/home#show"

  resources :staffs
  resources :staff_photos

  namespace :admin do
    resources :staffs
    resources :weixin_users
    resources :staff_photos do
      member do
        post 'change_valid'
      end
    end

    match '/roster_reset/staff' => 'roster_reset#staff'
    match '/roster_reset/photo' => 'roster_reset#photo'

    resource :session

    match '/' => redirect("/admin/staffs")
  end

end

bajiao-weixin/app/models/weixin_user.rb
# -*- encoding : utf-8 -*-
class WeixinUser < ActiveRecord::Base
  S_INVALID = 1 # 未通过
  S_VALID = 2 # 通过审核

  attr_accessible :nick, :remark, :weixin_id, :status, :query_count

  belongs_to :tmp_photo, :class_name => "StaffPhoto", :foreign_key => :tmp_photo_id

  # 初始创建用户，如果有了则不重复创建
  def self.firstCreate(xml)
    user = WeixinUser.where(:weixin_id => xml.from_user).first
    if user.nil?
      user = WeixinUser.create(:weixin_id => xml.from_user,
                               :status => S_INVALID, :query_count => 0,
                               :remark => Time.now.to_s + "\r\n" + xml.content)
    end
    return user
  end

  def is_valid?
    return status != S_INVALID
  end
end

bajiao-weixin/app/controllers/admin/weixin_users_controller.rb
# -*- encoding : utf-8 -*-
class Admin::WeixinUsersController < Admin::ApplicationController
  def index
    @weixin_users = WeixinUser.all
  end

  def edit
    @weixin_user = WeixinUser.find(params[:id])
  end

  def update
    @weixin_user = WeixinUser.find(params[:id])

    if @weixin_user.update_attributes(params[:weixin_user])
      redirect_to admin_weixin_users_url, :notice => '修改成功！'
    else
      render :action => "edit"
    end
  end
end

bajiao-weixin/app/helpers/weixin_users_helper.rb
# -*- encoding : utf-8 -*-
# -coding: utf-8 -
module WeixinUsersHelper

  def status_desc(weixin_user)
    case weixin_user.status
      when WeixinUser::S_INVALID
        "未通过"
      when WeixinUser::S_VALID
        "通过"
    end
  end
end

bajiao-weixin/app/views/admin/weixin_users/edit.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <%= render :partial => 'layouts/admin_nav', :locals => {:curr_tab => 'weixin_user'} %>

    <%= form_for([:admin, @weixin_user], :html => {:class => "form-horizontal"}) do |f| %>
        <% if @weixin_user.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@weixin_user.errors.count, "error") %> prohibited this weixin_user from being
                saved:</h2>

              <ul>
                <% @weixin_user.errors.full_messages.each do |msg| %>
                    <li><%= msg %></li>
                <% end %>
              </ul>
            </div>
        <% end %>

        <div class="control-group">
          <label class="control-label" for="inputEmail">微信ID</label>

          <div class="controls">
            <%= f.text_field :weixin_id, :readonly => true, :class => "input-xxlarge" %>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label" for="inputEmail">状态</label>

          <div class="controls">
            <%= f.select :status, [["未通过", WeixinUser::S_INVALID],["通过", WeixinUser::S_VALID]], :class => "input-xxlarge" %>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label" for="inputEmail">昵称</label>

          <div class="controls">
            <%= f.text_field :nick, :class => "input-xxlarge" %>
          </div>
        </div>

        <div class="control-group">
          <label class="control-label" for="inputEmail">备注</label>

          <div class="controls">
            <%= f.text_area :remark, :rows => 10, :class => "input-xxlarge" %>
          </div>
        </div>

        <div class="control-group">
          <div class="controls">
            <button type="submit" class="btn btn-primary">修改</button>
            <%= link_to '返回列表', admin_weixin_users_path, :class => "btn" %>
          </div>
        </div>
    <% end %>
  </div>
</div>

bajiao-weixin/app/views/admin/weixin_users/index.html.erb
<div class="container-fluid">
  <div class="row-fluid">
    <%= render :partial=>'layouts/admin_nav', :locals=>{:curr_tab=>'weixin_user'} %>

    <table class="table table-hover table-bordered">
      <thead>
      <tr>
        <th width="10%">#</th>
        <th width="20%">微信ID</th>
        <th width="20%">昵称</th>
        <th width="40%">备注</th>
        <th>状态</th>
        <th></th>
      </tr>
      </thead>

      <% @weixin_users.each.with_index do |user, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= user.weixin_id %></td>
            <td><%= user.nick %></td>
            <td><%= simple_format user.remark %></td>
            <td><%= status_desc user %></td>
            <td>
              <%= link_to "修改", edit_admin_weixin_user_path(user) %>
            </td>
          </tr>
      <% end %>
    </table>
  </div>
</div>