bajiao-weixin/config/routes.rb
Bajiao::Application.routes.draw do

  scope :path => "/weixin", :via => :post, :defaults => {:format => 'xml'} do
    root :to => 'weixin/home#welcome', :constraints => Weixin::Router.new(:type => "text", :content => "Hello2BizUser")
    root :to => 'weixin/staffs#show', :constraints => Weixin::Router.new(:type => "text", :content => /^@/)
    root :to => 'weixin/staff_photos#update', :constraints => Weixin::Router.new(:type => "text", :content=>/^#photo /)
    root :to => 'weixin/staffs#index', :constraints => Weixin::Router.new(:type => "text")
    root :to => 'weixin/staff_photos#create', :constraints => Weixin::Router.new(:type => "image")
  end

  get "/weixin" => "weixin/home#show"

  resources :staffs
  resources :staff_photos

  namespace :admin do
    resources :staffs
    resources :weixin_users
    resources :staff_photos do
      member do
        post 'change_valid'
      end
    end

    match '/roster_reset/staff' => 'roster_reset#staff'
    match '/roster_reset/photo' => 'roster_reset#photo'

    resource :session

    match '/' => redirect("/admin/staffs")
  end

end

bajiao-weixin/app/models/staff.rb
# -*- encoding : utf-8 -*-
class Staff < ActiveRecord::Base
  attr_accessible :name, :workno, :phone, :email, :dept, :duty, :username, :pinyin

  has_many :staff_photos, :foreign_key=>"staff_workno", :primary_key=>"workno"

  paginates_per 200
end

bajiao-weixin/app/controllers/admin/staffs_controller.rb
# -*- encoding : utf-8 -*-
class Admin::StaffsController < Admin::ApplicationController

  def index
    @staffs = Staff.page(params[:page])
  end
end

bajiao-weixin/app/controllers/staffs_controller.rb
# -*- encoding : utf-8 -*-
class StaffsController < ApplicationController
  def show
    @staff = Staff.where(:workno=>params[:id]).first
  end
end

bajiao-weixin/app/controllers/weixin/application_controller.rb
# -*- encoding : utf-8 -*-
class Weixin::ApplicationController < ActionController::Base
  layout "weixin"
  skip_before_filter :verify_authenticity_token
  before_filter :check_weixin_legality
  before_filter :check_weixin_user

  private
  # 根据参数校验请求是否合法，如果非法返回错误页面
  def check_weixin_legality
    array = [Rails.configuration.weixin_token, params[:timestamp], params[:nonce]].sort
    render :text => "Forbidden", :status => 403 if params[:signature] != Digest::SHA1.hexdigest(array.join)
  end

  # 检查微信用户是否合法
  def check_weixin_user
    @weixin_user = WeixinUser.firstCreate(weixin_xml)
    render "weixin/403", :formats => :xml unless @weixin_user.is_valid?
  end

end

bajiao-weixin/app/controllers/weixin/home_controller.rb
# -*- encoding : utf-8 -*-
class Weixin::HomeController < Weixin::ApplicationController
  skip_before_filter :check_weixin_user, :only => [:show]

  # 欢迎信息
  def show
    render :text => params[:echostr]
  end

  # 欢迎信息
  def welcome
  end
end

bajiao-weixin/app/controllers/weixin/staff_photos_controller.rb
# -*- encoding : utf-8 -*-
class Weixin::StaffPhotosController < Weixin::ApplicationController

  # 图片投稿
  def create
    @photo = StaffPhoto.new_by_msg(weixin_xml)
  end

  # 改变图片的归属
  def update
    workno = weixin_xml.content.split(' ')[1]
    @staff = Staff.where(:workno => workno).first
    photo = @weixin_user.tmp_photo
    if @staff.present? and photo.present?
      photo.update_attribute(:staff_workno, workno)
      @weixin_user.update_attribute(:tmp_photo_id, nil)
      render "update"
    else
      render "error"
    end
  end

end

bajiao-weixin/app/controllers/weixin/staffs_controller.rb
# -*- encoding : utf-8 -*-
class Weixin::StaffsController < Weixin::ApplicationController

  # 查找所有员工
  def index
    query = weixin_xml.content
    @staffs = Staff.where(["workno=? or phone=? or username=? or pinyin=? or name=? ", query, query, query, query, query]).limit(5)
    if @staffs.empty?
      render "not_found"
    else
      render "index"
    end
  end

  # 根据工号展示某个员工
  def show
    query = weixin_xml.content[1..-1]
    @staff = Staff.where(["workno=?", query]).first
    if @staff.nil?
      render "not_found"
    else
      render "show"
    end
  end

end

bajiao-weixin/app/helpers/staffs_helper.rb
# -*- encoding : utf-8 -*-
module StaffsHelper
end

bajiao-weixin/app/helpers/weixins_helper.rb
# -*- encoding : utf-8 -*-
# -coding: utf-8 -
module WeixinsHelper
  # 补全工号前面的0
  def pretty_workno(workno)
    "0" * (6 - workno.length) + workno
  end
end

bajiao-weixin/app/views/weixin/staffs/_list.erb
<% staffs.each do |staff| %>
<%= staff.name %> #<%= staff.phone %>
[ <%= pretty_workno staff.workno %> ]
<%= staff.dept %>
<%= staff.duty %>
<%= staff.email %>
<% if staff.workno == '672' %>
<%= "\u{1F389}" %>伟大的作者<%= "\u{1F47B}" %>
<% end %>
<% if staff != staffs[-1] %>
───────────
<% end %>
<% end %>

bajiao-weixin/app/views/weixin/staffs/index.xml.erb
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[<%= render :partial=>"list", :locals=>{:staffs=>@staffs} %>]]></Content>

bajiao-weixin/app/views/weixin/staffs/not_found.xml.erb
<MsgType><![CDATA[text]]></MsgType>
<Content><![CDATA[啊哦……没找到/:,@!……
<%= render "weixin/help" %>]]></Content>

bajiao-weixin/app/views/weixin/staffs/show.xml.erb
<MsgType><![CDATA[news]]></MsgType>
<ArticleCount>1</ArticleCount>
<Articles>
    <item>
        <Title><![CDATA[<%= @staff.name %>]]></Title>
        <Description><![CDATA[点击查看详情...]]></Description>
        <PicUrl><![CDATA[<%= staff_photo_url(@staff.staff_photos[0].id) %>]]></PicUrl>
        <Url><![CDATA[<%= staff_url(@staff.workno) %>]]></Url>
    </item>
</Articles>